### ISSUE TITLE
Shuffled Skultulas

### ISSUE THREAD

**Issue by Archer262** [jupiter0fire/OoTMMR_tracker_pack#41]
Currently the OOT setting for showing shuffled Skultulas is bugged. Having it set to overworld only shows both overworld and dungeon skulls, the other settings are working.

**Comment by jupiter0fire** [comment]
thanks for reporting the bug! will fix it in the next few days, but I am not sure when we will make the next release

**Comment by jupiter0fire** [comment]
fixed with the release 1.12.4.1
