### ISSUE TITLE
Bombchu Bag Logic

### ISSUE THREAD

**Issue by alwayzb114** [jupiter0fire/OoTMMR_tracker_pack#50]
Hello,

Unless I am missing anything, I don't see a setting for Bombchu Bag to be enabled and considered in logic. Is this not implemented, or am I simply blind?

Thank you!

**Comment by Onemario1234** [comment]
This tracker is currently very outdated, and was created before Bombchu Bags were added.

A new, updated tracker is being worked on, but is not publicly available yet.

**Comment by jupiter0fire** [comment]
Yes, the tracker pack is still based on randomizer version 1.12.4, so all of the newer settings aren't supported at the moment. We plan to update the tracker pack to the current randomizer version at some point. There are also some other people working on an update which is probably what Onemario is referring to.

**Comment by alwayzb114** [comment]
Great, thank you both for the info. In the meantime, checking regular Bombs when I get Bombchu Bag seems to do the trick for the most part. Outside of a few edge cases (like defeating Dodongo without glitches to get the bombchu in his mouth, or MM Honey and Darling games), the bomb and chu logic are about the same.
