### ISSUE TITLE
tracker isn't showing all locations

### ISSUE THREAD

**Issue by elhuntero** [jupiter0fire/OoTMMR_tracker_pack#58]
some of the MM dungeons are not showing all locations, for example woodfall:
it seems to be mostly fairy locations. Stone Tower Temple is fine.
![Capture](https://github.com/user-attachments/assets/80431db1-4a98-4ec5-8f67-7b2cbdc25a9d)

**Comment by jupiter0fire** [comment]
we talked on discord and dungeon freestanding fairy shuffle was not enabled
